---
title: Effective, flexible utility of Myers Briggs Type Indicators 
author: Teodor Heggelund
date: 2018-01-05
---

Keywords: /philosophy/, /principles/, /psychology/, /psychonometrics/.

I want to understand.

Over time, I gradually want to increase the radius of my understanding.
Classical mechanics is well-defined and coherent. The human condition less so.
Yet, we can still build an understanding of each other -- if we allow for some
other tools to enter.

Physical models are often deterministic. If a set of preconditions are present,
the result can be predicted. In practice, this works extremely well. Mechanical
models used by civil engineers typically have margins of error less than 5 %,
often negligibly close to zero.

Psychological models are a different breed. Current psychological models have
nowhere near the predictive capability of physical models. As humans are vastly
more complex than point masses with momentum and angular momentum, we may never
have a total model of a human being.

/We are not able to enclose the totality of human behavior within a model./

As we are not able to create a /total model/ of humans, we must be sure not to
interpret the results in a total way. We can never really predict behavior --
yet we may improve our first guesses significantly.
Models can be useful without promising confident predictions.
If I know I will be meeting new people, I may try to activate
different parts of my identity as opposed to when I am trying to understand
something hard. With vocabulary from the model, it is easier to formulate what
that activation /means/.
The model helps me pull parts of my identity into the conscious.
Only then can I make a real conscious effort to behave in the way I intend.

** Commentary                                                     :noexport:
/This headline is not exported into the final document./
*** First draft outline
- Myers-Briggs Type Indicators (MBTI)
  - Define MBTI
- On the approximations of MBTI
  - Discuss limitations of MBTI
- From dogma to tool
  - Discuss mode of utility for MBTI
- A tool for expression
- A tool based on positive utility
- From type to mode of being
- Different modes of being are preferred in different situations
- Use your type to improve your weaknesses
- References
*** On the writing process
1. Should I bring in more sources? That would be different depending on the
   degree of scrutiny I want for the essay.
   - Do I want to communicate something based on the thoughts of others?
   - Or this a recollection of personal experience, allowing others to live
     through it and determine if it is valuable to them?
*** Why even do this?
I want to understand.

Over time, I gradually want to increase the radius of my understanding.
Classical mechanics is well-defined and coherent. The human condition less so.
Yet, we can still build an understanding of each other -- if we allow for some
other tools to enter.

Physical models are often deterministic. If these preconditions are present, the
result can be predicted. In practice, this works extremely well. Mechanical
models used by civil engineers typically have margins of error less than 5 %,
and often negligibly close to zero.

Psychological models are a different breed. Current psychological models have
nowhere near the predictive capability of physical models. As humans are vastly
more complex than point masses with momentum and angular momentum, we may never
have a total model of a human being. There may never be a time when we can
confidently predict the actions of a human being. I hope that will never be the
case.

We are not able to enclose the totality of human behavior within a model.

As we are not able to create a /total model/ of humans, we must be sure not to
interpret the results in a total way. We can never really predict behavior --
yet we may improve our first guesses significantly. Models can also be used as
pure tools. If I know I will be meeting new people, I may try to activate
different parts of my identity as opposed to when I am trying to understand
something hard. With vocabulary from the model, it is easier to formulate what
that focus /means/.
** Myers-Briggs Type Indicators (MBTI)
Theory on Myers-Briggs Type Indicators assert that individuals have preferred
mental tools, and that these change between individuals. A personality profile
is described along four axes:

- Extroversion (E) or introversion (I);
- Sensing (S) or intuition (N);
- Thinking (T) or feeling (F); and the last,
- Judging (J) or perceiving (P).

A person who is relaxed around people (E); prefers near, well-defined details
(S); trusts in her feelings (F); and takes opportunities as they come (P) --
will be classified as an ESFP. A person who prefers time alone to work things
out (I); likes to consider big picture effects (N), bases decision making on
logic (T) and plans far ahead (J) will be classified as an INTJ.

To get classified, one may take the test on [[http://www.16personalities.com][the 16 Personalities website]]. The
result will be a four letter indicator and a ratio for the position on each
axis. The 16 Personalities test also gives a fifth axis which I will not explain
 here.

# TODO: explain percentages and examplify my own. "Really like long term", but
# "can be opportunistic with planning".

MBTI describes preferred mental tools; preferred mental models. That does not
cause inability of mode of operation outside of one's preference -- only
increased effort to exit the comfort zone. In other words, MBTI describes our
behavior when walking the path of least resistance.
** On the approximations of MBTI
Wikipedia lists up both theoretical and empirical criticism of Myers-Briggs
Type Indicators[fn:wikipedia-mbti-criticism]:

#+BEGIN_QUOTE
Although popular in the business sector, the MBTI exhibits significant
psychometric deficiencies, notably including poor validity (i.e. not measuring
what it purports to measure) and poor reliability (giving different results for
the same person on different occasions).
#+END_QUOTE

As a scientific model, MBTI has serious drawbacks.

- Test error: How wrong is the test you take?
- Model error: How wrong are the four chosen axes? They were just decided by
  some people in the 20th century.
- Model error: How wrong is it to assign a pure number to each axis? The
  model is /by purpose/ designed to measure preference. Preference correlates
  with skill, but /it is not the same/. Some people have well developed
  multi-faceted modes of being.

These drawbacks are in my opinion major. As I cannot fully trusting console the
approximations made with reality, I am left to only be able to take MBTI as a
non-total approximation. It cannot describe the totality of a personality, and
it should therefore not be presumed that a MBTI type is sufficient for a good
understanding of a human being.
** From dogma to tool
A classification can be a procrustean bed that limits our perception. I prefer
thinking of the type indicators as a starting point for understanding a person.

How should we approach personality? Is personality something we may ever totally
understand? Will we finally have a total understanding of how the human mind
works? This question has troubled the mind of many a man over the course of
mankind. We attempt to answer this question in a multitude of fields.
Neuropsychology attempts to explain how we think with science. The humanities
use literature to describe the human condition. Religion provides principles for
how we should act when facing totality.

When we apply scientific rigor, we will only be able to 
# TODO

We can say very little with scientific confidence.
# TODO

MBTI is a phenomenological tool. It describes the human experience. Its utility
should be derived from that. Phenomenology is the study of the human experience
and consciousness.
# (That's convenient -- when we're describing humans!)
# Meta. We're using a framework based on human experience to describe human
# experience; no need to reduce via science.
# Have you ever tried to describe your emotions with pure science -- compared to
# anectodally?

** A tool for expression
Since MBTI gives an indication of a personality's preferred mode of being, it
can give aid as to how an argument should be presented in order to effectively
communicate. For an audience strong on S (sensing), thoughts should be
concretized as much as possible, and metaphysical arguments avoided. For
feelers, the impact of the decision on people should be discussed.

*TODO.*
** A tool based on positive utility
Personal opinion: focusing on the positive utility of a type is useful. Think of
how and where a given type can be useful. How should one then compose a
multi-typed team? Who should have what responsibility?

Note: Respect people's need for getting out of their comfort zone and taking on
new challenges.

*TODO.*
** From type to mode of being
Reading up on the theory may give the impression that /one/ class is right for each
person. I will argue that it may be useful to look at the type indicator as a
mode of being for a person. In a different situation, the same person may be
better described by a different personality type.

*TODO.* Argument: Model error and meta-model error makes total reasoning
problematic. Should we instead choose to make weaker statements about people, we
may increase utility.
** Different modes of being are preferred in different situations
*TODO.* The value of different types depends on the context. What about trying
to choose to embrace traits based on the situation one is in?
** Use your type to improve your weaknesses
When you don't make an effort, you will fit in your type and follow your
preference. Go out of your comfort zone and try other modes of being to improve
on the places where you are weak.

People easily get good at what they like doing. The type can open one's eyes to
what traits they may need to improve. *TODO.*
** References
[fn:16personalities]: [[https://www.16personalities.com][16 Personalities]] offers a free test to determine your Myers Briggs Type Indicator, descriptions of 16 types predicted by the test, and an overview on the underlying theory.

[fn:wikipedia-mbti-criticism]: TODO link. Quote from overview, link to criticism-specific section.
