---
title: Intersecting philosophies of Jordan Peterson, Brandon Sanderson and Nassim Nicholas Taleb
author: Teodor Heggelund
date: 2018-03-27
---

The intersection is interesting.

Peterson utters that to speak truth is to be powerful. Surgebinders in
Sanderson's tales have to speak the ideals before progressing.

Taleb speaks of risk taking and skin in the game as a foundational virtue.
Carrying a load as heavy as one can manage is considered by Peterson to be the
only worthwhile quest there is.

- /Truth/ is considered powerful by all.
- /Individual responsibility/ is considered the essence of virtue or progress.

** Purpose, ratification, orientation, focus.
I never completed this text. I've had it stuck in the drafts folder for half a
year. My current diagnosis is /waaaay/ to wide a topic. I want to do a
wide-ranging analysis of the philosophies of three /really/ complex thinkers?

So what is the common ground? I say the hero's journey. The hero myth. That's
the underlying part of each thinker's philosophy that I can resonate with. Acta
non verba. Act for good.
*** Peterson's responsibility
Pick up your cross and carry it. Take some goddamn responsibility, and go make
your life worthwhile. Make the world so that you'd like to live in it. Improve
it. Improve yourself. Make yourself strong.

I cannot really encompass all that Peterson is. There's too much. Instead, as
seen above, I fall back on partial description. Illustration. Dramatization.
*** Sanderson's heroes
Sanderson's heroes are the best heroes I've read. I first encountered his
writing in the final stages of an epic 14 book fantasy series. The original
author -- Robert Jordan -- had died of cancer. The series had immense depth, and
a dedicated following.

When I started reading the first book where Sanderson's pen had been involved, I
was worried. I was so engulfed in the series already. Please don't destroy Wheel
of Time. There's so much here.

Well into the book, I didn't notice anything that felt off. I was slightly
surprised. Shouldn't this feel different? Less solid, somehow? A little strange,
a little unfamiliar? It didn't. The book felt at home. The characters didn't
bleach, they came closer, saturated in color, differentiated by what made them
special. Finally, I came to the uncomfortable conclusion that had been hauting
my mind for some time. I liked Sanderson's continuation of Wheel of Time better
than the beginning. No one beats Robert Jordan in the crafting of epic fantasy.
Sanderson got a superb tie in the contest of epic proportions. In addition, he
brought the story closer. The personalities were more real. The daily
progression no longer felt like a filler. I enjoyed the small meetings with the
characters.
*** Taleb's criticism of intellectualism
Taleb's ethics? Taleb's anti-intellectual criticism? Dunno. I liked Antifraglie
because it took seriously the cost of over-complicating models. I picture Taleb
meeting Peterson where Peterson's aversion to unreal conversation, conversation
with the animus or the anima merge with Taleb's intelligensia aversion, Taleb's
take that action is paramount, models second, if you cannot say how one should
act in a certain situation, your model is disconnected.
