---
title: Commentary on Ray Dalio's Principles
author: Teodor Heggelund
date: 2017-10-29
---

Keywords: /filosofi/, /prinsipper/.

I am thoroughly impressed with Ray Dalio's [[https://www.principles.com][/Principles/]]. /Principles/ is a
description of a philosophy of life founded on principles. Dalio searches
actively in his own experience, out of which he attempts to produce principles
for how to act.

A central theme in the book is the process surrounding the principles:

- How does one make decisions based on principles?
- How to change a principle that produces bad results?
- How can one develop new principles?

I believe his approach can be useful for people with a principled mindset --
including me. This text is my attempt at making the principles my own. How to
these principles apply to me? How do I judge them? Do I have specific examples
or experiences, that can help ground the principles and give them context?

The principles are formulated in three levels. Level one principles are broad
and general, and may contain level two and level three principles, which are
more specific. This text retains the hierarchical structure of the principles,
with my commentary.

- Embrace reality and deal with it.
  - Be a hyperrealist.
    - Dreams + Reality + Determination = A Successful Life.
  - Truth---or, more precisely, an accurate understanding of reality---is the
    essential foundation for any good outcome.
  - Be radically open-minded and radically transparent.
    - Radical open-mindedness and radical transparency are invaluable for rapid
      learning and effective change.
    - Don't let fears of what others think of you stand in your way.
    - Embracing radical truth and radical transparency will bring more
      meaningful work and more meaningful relationships.
  - Look to nature to learn how reality works.
    - Don't get hung up on your views of how things "should" be because you will
      miss out on learning how they really are.

* Utility                                                          :noexport:
How can I make use of this?

I did not finish Dalio's /Principles/. Why is this? It could be that there was
too much theorizing. It could be that I was unable to disipline myself
sufficiently. Regardless: how do I progress? He seems to have wanted to write
down a bunch of things. Yet -- he says that the principles he writes down are
his own, and that others would have to find /their/ unique set of principles.
