---
title: Python-kurs for NTNU Konstruksjonsteknikk
author: Teodor Heggelund
date: 2018-11-05
---

/05. november 2018/

Praktisk informasjon følger. Vel møtt!

** Hva trenger jeg å gjøre før kurset?
Vennligst installer Anaconda Python 3.7 før kurset begynner. Nedlastingen er
stor (500 MB) og tar etterpå en tid å installere (ca 10 minutter). For link, se [[Kursmateriell]].
** Agenda
- *Intro*. Hvorfor er vi her?
- *Del 1: Python-programmering med Jupyter Notebooks*. Vi lærer å kjøre kode i
  Jupyter Notebooks, og går gjennom grunnleggende Python.
- *Del 2: Vitenskaplig programmering med Python.* Python fungerer godt for
  vitenskaplig programmering fordi Python har et svært godt sett med
  tredjepartsbiblioteker. Etter at vi har sett hvordan vi kan få tilgang til
  disse, og hvordan vi bruker et utvalg.
- *Del 3: Samhandling med Jupyter Notebooks.* Når bør vi dele en notebook? Når
  bør vi dele en pakke? Hvordan pakkes Python-kode? Hvordan installerer vi en
  pakke lokalt? Hvordan bruker vi en egen pakke i en Notebook?
- *Finale*. Hvor går veien videre?
** Kursmateriell
- Nedlasting av Python-distribusjon: [[https://www.anaconda.com/download/][Anaconda Python 3.7 64-bit]]. Lokal
  installasjon av Anaconda gir best brukeropplevelse. Alt gikk bra hvis du kan starte
  *Jupyter Lab*. 
  - Nødløsning for de som ikke
    for installert Anaconda er mulig med [[https://mybinder.org/v2/gh/teodorlu/ntnu.kt/master][Binder]] (kun Jupyter Notebook, ikke
    Jupyter Lab).
- Slides brukt under kurs fra [[https://purelogicno-my.sharepoint.com/:p:/g/personal/th_purelogic_no/EZ79NhD9NnZJt91Zf6W1FOQBcD63mzHTlKPfAsDXfXi11g][Office Online]] eller som [[../static/kurs_2018-11-05_slides.pdf][PDF]]
- Materell (Notebooks, python-moduler) er tilgjengelig  på [[https://github.com/ntnu-kt/ntnu.kt][Github]]. Min intensjon
  er at KT tar over eierskap.
- Pakke brukt i del tre er publisert til [[https://pypi.org/project/ntnu.kt/][Pypi]]. Min intensjon er at KT tar over
  eierskap. Innholdet i pakken er foreløpig kun for demonstrasjon av mulig
  infrastruktur.

For de som er kjent med Matlab, kan jeg anbefale [[https://www.enthought.com/wp-content/uploads/Enthought-MATLAB-to-Python-White-Paper.pdf][migrasjonsguiden fra Matlab til
Python utgitt av Enthought]] (PDF) ([[https://www.enthought.com/white-paper-matlab-to-python/][alternativ link]]). Enthought er blant de som
lager Scipy.
** Hvordan bør jeg følge opp etter kurset for godt læringsutbytte?
Jeg har tro på læring i eget tempo. Da kan man bruke tid der man trenger, og
stoppe opp når man har spørsmål. En felles gjennomgang blir aldri helt det
samme, for der må alle følge samme tempo. Kurset gikk heller ikke grundig
gjennom alt som er å lære.

Jeg anbefaler derfor for å få godt utbytte av kurset:

/Last ned notebooks fra Github (se Kursmateriell), gå gjennom slides og prøv å
kjøre kode selv for å se om resultatet blir som du forventer./

Enkleste måte å kjøre koden på er å lage en blank Notebook selv og copy-paste
fra Github.
