---
title: Commentary with Hypothesis
author: Teodor Heggelund
date: 2018-05-27
---

[[http://web.hypothes.is/][Hypothesis]] may be able to provide proper discussion for any web site. Sounds
interesting? Read on to learn how Hypothesis can provide interaction to the web
in a good way.

/Why do I care? And why should you care?/

The Internet just works, doesn't it? I will begin by taking a step back. You are
reading this text from a web browser. The web browser does not, however, only
understand the text of the document. It also understands its semantic structure.
Division into paragraphs is an example of semantic structure. You've double
clicked to open documents before. Why don't you try to triple-click *here*?

Your web browser is not only able to show you the content of this page, it also
understands what a paragraph is. This is possible because what you are seeing is
a /semantic document/.

What are examples of things that are not semantic documents? An audio file does
provide semantic information about where a paragraph begins and ends. A video
file does not provide semantic information about filmed text. A human may be
able to recognize a paragraph is, but a machine may not reliably do so.

/But how is this useful?/

The fact that the Internet is divided into documents that stay at the same
Internet address is the reason that you are actually able to find things on
Google. Ever tried searching for a paragraph inside a video file or an audio
file? That's pretty hard. Another challenge is differentiating between [[https://en.wikipedia.org/wiki/Homonym][words
that sound the same]]. The Internet is composed of stable, semantic documents.

/... what about commentary?/

Commentary is not stable by nature. Commentary is interaction, change. It does
not fit well into the realm of stability of the Internet. Put a comment in some
comment box on some random site? How will you know if someone replies? Will you
note all the places you ever made a note on the Internet? Or will you just /not
make notes/? I tend to not bother with commenting on what others publish on the
Internet for this exact reason. Here's where Hypothesis comes in. I will state
this about Hypothesis:

- /Hypothesis is the proper semantics for commentary./ Comments are not sent
  away into the ether, never to return. You can organize them all, centrally.
  You can edit your own comments. You can search in them.
- /Hypothesis is not owned by the site you visit./ Facebook and Google may own
  half your digital life already. Recent media coverage has shown us that
  Facebook's use of our data may not be the way we wanted. The proper response
  is not giving that data away in the first place.
- /Hypothesis provides proper interaction for commentary and annotation./ You
  can annotate anything you see on a web site. You can comment on the document
  instead, if you prefer. You can comment on someone else's comment.

I do not want to own your comments. I want /you/ to own them. If you own them,
you can easier take responsibility for them. You can follow up on something
that's important. You can delete them if you need to. You can publish with the
knowledge that you can respond.

This is where Hypothesis comes in.

- Your comments are your own, not the property of the site you visit. Hypothesis
  is a non-profit aiming to tackle this problem in the proper way.
- You annotate and comment the same way on any web page by installing the
  browser extension. As a developer, I can tailor to the use of Hypothesis over
  other options, and have it automatically load.
- No need to create a bunch of one-off accounts for commenting all over the web.

/So how does one use Hypothesis?/

Looking to annotate pages and comment? Check out [[https://web.hypothes.is][hypothes.is]] on how to get
started.

Looking to integrate Hypothesis into your own Web site as with this one? Include
this snippet on the pages where you want Hypothesis to load:

#+BEGIN_SRC html
  <script type="application/json" class="js-hypothesis-config">
    {"showHighlights": false}
  </script>
  <script src="https://hypothes.is/embed.js" async></script>
#+END_SRC

That's all for now!
