---
title: "Grad av kontroll i lederskap"
author: Teodor Heggelund
date: 2017-09-24
lang: "no"
---

Stikkord: /ledelse/.

Delegering er vanskelig.

- Ting blir bra fordi du jobber hardt med detaljer
- Om du "jobber hardt med detaljer når du delegerer" vil du drive personene som
  jobber med deg fra vettet.
  - De gjør en dårligere jobb,
  - Tar ikke ansvar,
  - Tar ikke initiativ
  - ... og du er fremdeles tynget med mental last.

Intenst ansvar kan gjøre at resultatet blir bra. Det kan også forhindre andre i
å ønske å bidra.
** Delegering på Elm-kurset
I begynnelsen under Elm-kurset gjorde jeg alt som trengtes for å få kurset til.
Jeg definerte hva vi skulle lære, la planen for hvordan å bygge opp kunnskapen
til deltagerene til dette nivået, videreformidlet hva vi skulle gjøre til andre
veiledere, tok styring på selve kurset, og fulgte opp og satte erfaringer i
system i etterkant. Jeg definerte det som var. Kurset ble solid; og var
fullstendig avhengig av meg.

Neste steg var å spre evne og ansvar til andre veiledere. Dette er faktisk
lettere når det allerede er et system! Det finnes informasjon. Det er en
etablert måte å gjøre ting på. Det er noen som kan sette presedens, som andre
stoler på. Kort fortalt -- vi høster fordelene av lederskap. Å ha et strukturert
Elm-kurs med gode ressurser er et resultat jeg er fornøyd med. Det er imidlertid
ikke nok. Hvordan skal kurset leve videre? Løsningen er å bygge kultur. Andre må
få innsikt i hva som er gjort; så vi ikke lenger bærer risiko på kun meg.

/Min motivasjon for delegering er forbedring av systemets potensiale over lang
tid./

Hva gjør dette med kontrollen? Når /jeg/ leverer, setter jeg /mine/ krav til
produktet, slik at det følger /min/ standard. Når jeg jobber følger jeg denne
implisitt. Jeg trenger ingen eksplisitt representasjon av min standard.

Det gir utfordringer under teamarbeid. Hvem sin standard setter presedens? Hva
er godt nok? Dette er vital informasjon som bør kommuniseres til teammedlemmer
underveis. Hva forventes? Hva er prosessen? Er du ferdig når du sender meg;
eller gjør vi revisjoner? Er vi enige om din rolle og din innsats?

Utfordringene er også følelsesmessige. Når jeg ikke leverer til min standard,
føler jeg meg dårlig, jobber for å forbedre, og blir fornøyd. Når andres arbeid
ikke lever opp til min standard, vet ikke engang de andre hva som er
forbedringspotensialet! Hvordan kan denne prosessen gjøres bedre?

- *Avklaring av forventinger* kan gjøre det tydelig hva som er arbeidsmengden i
  forkant, og reduserer risikoen andre tar ved å legge inn sin tid. De får mer
  helhetsforståelse, og kan lettere si ja eller nei i utgangspunktet.
- *Spesifikke krav til produktet* er god tilbakemelding som er lett å fikse.
  "Kan du gjøre rede for hva ~map~ gjør?" "Her bruker du ~Svg.rect~ -- hvor kom
  denne fra?"
- *Prinsippielle krav til produktet* er mer krevende tilbakemelding. "Jeg synes
  ikke dette avsnittet er godt nok." "Jeg synes du bruker for lang tid før det
  er mulig å teste om hva du har gjort fungerer eller ikke." Gjør det eksplisitt
  at disse tilbakemeldingene er subjektive; så er det lettere for andre å tolke
  tilbakemeldingene på rett måte.
- *Prosessfokus* er vital tilbakemelding til samarbeidspartnere. Hva gjør vi? Er
  produktet godt nok til å legges ut nå? Er det bra når vi har fikset disse
  tingene? Hva skjer typisk når vi legger til nye oppgaver; skal resultatet
  brukes umiddelbart eller er det hensiktsmessig med en runde forbedringer?

Personer har svært forskjellige forhold til delegering. Noen har null problemer
med å delegere, fordi de ganske enkelt ikke bryr seg om resultatet etter at
resultatet er vekk fra egen tallerken. Andre har svære problemer med å delegere
fordi de ikke klarer å gi slipp på ansvaret.
** Ledelse -- tjenestebasert eller styrende?
Hvilken fordeling av kunnskap ligger til grunn for ledelsen?

1. Ledelse under forutsetning om at én person har oversikt
   - Hierarki-basert
2. Ledelse under forutsetning om at ingen enkeltentiteter vet nok
   - Nettverk-basert

Virkeligheten er grå. Det er aldri noen som vet alt. Så hvordan finner man en
middelvei? Vi kan tilføre verdi gjennom lederskap på forskjellige måter:

- *Ledelse i tjeneste*. Du kan spørre meg om dette når du har behov. Jeg
  kommer med min mening. Du tolker denne; og prøver å gjøre som best du kan
  basert på hva jeg sier. Du kan bruke hva jeg sier ordrett eller bygge på en
  viss grad av tillit.
- *Ledelse i hierarki*. Vil følger alle /denne/ prosedyren. Du får dette, du
  leverer dette. Hierarkier gir god forutsigbarhet for de som forholder seg til
  arbeidsprosessen. Hierarkiledelse sørger for stor grad av likhet i prosjekter.
  Det kan garanteres invarianter mellom prosjekter. "Introduksjonsinformasjonen
  ligger alltid /her/; og du finner /her/ en oversikt over hvem som er
  involvert". Vi sikrer kohesjon, som effektiviserer informasjonsflyt og skaper
  verdi.

Hvordan formidler vi hvilken informasjon vi har? En modell som ligger nær
tjenester er fakta + forslag.

- *Fakta*: her er informasjon som kan være nyttig.
- *Forslag*: ut ifra min erfaring ville jeg begynt med en prosedyre som ser slik
  ut. Hvis du ikke veit hvordan du kan starte, kan dette være en god ting.

Fakta booster nytten av analyse. Det blir lettere å trekke rett logisk slutning
når du har mer fakta. Fakta er av natur analytisk. Du får byggesteiner som du
kan sette sammen på egen måte selv. Helheten blir naturlig vanskeligere å
formidle; da denne ikke kun er basert på fakta, men i tillegg erfaring og
intuisjon. Erfaring og intuisjon kan ikke reduseres i logiske biter på samme
måte som fakta og logikk, men kan gi en helhetsløsning.
** God ledelse?
Typen ledelse jeg er komfortabel med stemmer godt med prinsippene over. Jeg
ønsker frihet og mulighet til å tenke selv. Andre ønsker en annen type
kommunikasjon.

Hvilken type ledelse som er optimal er ekstremt avhengig av typen problem. Hva
er kostnaden av en feil på et sykehus? Hva er kostnaden av smal tankegang
grunnet kortsynt ledelse? Dette er prinsipper jeg tar i bruk når jeg lurer på
hvor jeg bør legge meg.
** Referanse: Utvikling i militærorganisasjoner for håndtering av mer komplekse problemer
Gjennom massemedia og informasjonsteknologi har vår evne til å prosessere og
kommunisere kompleks data gått i taket. Bedre verktøy har latt oss løse helt
andre klasser problemer enn tidligere. Samtidig eksploderer graden av
kompleksitet -- siden det er mer lønnsomt å lage komplese systemer enn før.

Økt kompleksitet gjør hierarkisk ledelse mindre egnet enn før, og vi bør
revurdere fordelingen av kontroll.

[[https://www.goodreads.com/book/show/4402576-power-to-the-edge][Power to the Edge av Richard E. Hayes og David S. Alberts]] setter
informasjonsutveksling i militære organisasjoner i system. Informasjonsmengde i
krigføring har eksplodert de siste hundre årene, og militæret fra 1700-tallets
Preussen er ikke lenger anvendbart for dagens utfordringer. Han skisserer så
endringer som gjør organisasjonene bedre egnet til å håndtere informasjonen, og
beskriver hvordan den type endringer har blitt gjort i forskjellige stater.
