---
title: Effective, flexible utility of Myers Briggs Type Indicators 
author: Teodor Heggelund
date: 2018-01-20
---

Keywords: /philosophy/, /principles/, /psychology/, /psychonometrics/.

I am driven by my need to understand.

I want to increase the radius of my understanding continuously.
Through my education, I have gotten a grip on classical mechanics.
Classical mechanics describes the motion of bodies under the influence of forces.
Classical mechanics is well-defined and coherent.
The human condition less so.
Yet, we can still build an understanding of each other -- if we allow for some
other tools to enter.

Physical models are often deterministic.
If a set of preconditions are present, the result can be predicted.
In practice, this is extremely useful.
Mechanical models used by civil engineers typically have margins of error provably
less than 5 %, often negligibly close to zero.
Because the error is /bounded/ -- provably below some limit -- we may
confidently predict behavior within a bounded error.
If we want to prove that a structure is safe under some load, and know that our
margin of error is less than 2 %, we can simply design the structure for a load
that is 2 % bigger, and safety is guaranteed.

Psychological models are a different breed.
Humans are vastly more complex than point masses with momentum and angular momentum.
Current psychological models have nowhere near the predictive accuracy of
physical models.
The margin of error is typically not bounded, and scientific models describe
correlation and probability instead of predicting behavior.

We are not able to enclose the totality of human behavior within a model.

As we are not able to create a /total model/ of humans, we must be sure not to
interpret the results in a total way.
We can never really predict behavior -- yet we may improve our first guesses
significantly.
Models that do not confidently predict behavior can also be useful.
If I know I will be meeting new people, I may try to activate different parts of
my identity as opposed to when I am trying to understand complicated theory.
With vocabulary from the model, it is easier to formulate what
that activation /means/.
The model helps me pull parts of my identity into the conscious.
Only then can I make a real conscious effort to behave in the way I intend.

** Commentary                                                     :noexport:
/This headline is not exported into the final document./
*** Draft and notes
**** Introduction
Motivation. Why bother? Where am I coming from?
**** Myers-Briggs Type Indicators (MBTI)
Define the system. What are type indicators. How are they determined. How do we
use them.
**** On the approximations of MBTI
Error in questionaire.
Error in model.
**** From dogma to tool
Shell pragmatic use of MBTI.
**** A tool for expression
- SNIP -
**** A tool based on positive utility
**** From type to mode of being
**** Different modes of being are preferred in different situations
**** Use your type to improve your weaknesses
**** References
*** Concepts 'up for consideration'
**** Context dependence in communication
Context dependence in understanding is interesting, but does it really belong
here?
***** Proposed text
Context may also be different. What seems obvious to me may not be obvious to
others, who have different frames of mind. Context dependence I can argue
explicitly, attempting to lay out all important considerations. When this is the
case, other people may judge the argument based on the explicit reasoning alone.
Explicit reasoning demands skill in the mode of thinking for the listener.
However, when what skill is present, When the thought process is mostly implicit
and inductive, more trust is needed.
*** On the writing process
1. Should I bring in more sources? That would be different depending on the
   degree of scrutiny I want for the essay.
   - Do I want to communicate something based on the thoughts of others?
   - Or this a recollection of personal experience, allowing others to live
     through it and determine if it is valuable to them?
*** Headlining arguments
Thesis: how to make use of MBTI.

Value propositions:

- Aid in effectively communicating with people of other types from yourself.
  - This is valuable.
- "Focus on positives"
  - Platitude?
  - Removed
- Adapt to the right mindset for a specific situation
  - Make explicit.
- Raise awareness of your own weaker modes.
  - Then build them!
*** Metacomment
I am getting overly theoretical. I should be bringing this directly from
practical experience, and not going on at length about something I think.

- I am experiencing increased SJ in Japan; a focus on the specific planning.
  By being more specific and allowing for a bit more planning in advance, I can
  utilize the system. Clerks are able to give accurate answers, and the hotel is
  able to plan properly in advance.
- In some restaurants, I have experienced hosts tending towards EFP. That is the
  case when you should start talking and get to know people! They tend to be
  really easy to get along with.
** Myers-Briggs Type Indicators (MBTI)
Theory on Myers-Briggs Type Indicators assert that individuals have preferred
mental tools. A personality profile is described along four axes:

- Extroversion (E) or introversion (I);
- Sensing (S) or intuition (N);
- Thinking (T) or feeling (F); and the last,
- Judging (J) or perceiving (P).

A person who is relaxed around people (E); prefers near, well-defined details
(S); trusts in her feelings (F); and takes opportunities as they come (P) --
will be classified as an ESFP. A person who prefers time alone to work things
out (I); likes to consider big picture effects (N), bases decision making on
logic (T) and plans far ahead (J) will be classified as an INTJ.

To get classified, one may take the test on [[http://www.16personalities.com][the 16 Personalities website]]. The
result will be a four letter indicator and a ratio for the position on each
axis. The 16 Personalities test also gives a fifth axis which I will not explain
here.

# TODO: explain percentages and examplify my own. "Really like long term", but
# "can be opportunistic with planning".

MBTI describes preferred mental tools; preferred mental models; a preference for
operation.
Preference does not imply inability to do something else -- only increased
effort to exit the comfort zone.
In other words, MBTI describes our behavior when walking the path of least
resistance.
** On the approximations of MBTI
Wikipedia lists up both theoretical and empirical criticism of Myers-Briggs
Type Indicators:

#+BEGIN_QUOTE
Although popular in the business sector, the MBTI exhibits significant
psychometric deficiencies, notably including poor validity (i.e. not measuring
what it purports to measure) and poor reliability (giving different results for
the same person on different occasions).
#+END_QUOTE

As a scientific model, MBTI makes several approximations:

- Test error: How wrong is the test you take?
- Model error: How wrong are the four chosen axes? They were just decided by
  some people in the 20th century.
- Model error: How wrong is it to assign a pure number to each axis? The
  model is /by purpose/ designed to measure preference. Preference correlates
  with skill, but /it is not the same/. Some people have well developed
  multi-faceted modes of being.

I find these drawbacks to be significant.
As I cannot fully trusting console the approximations made with reality, I am
left to only be able to take MBTI as a non-total approximation.
MBTI cannot totally describe a personality, and it should therefore not be
presumed that a MBTI type is sufficient for a good understanding of a human
being.
** From dogma to tool
A classification can be a procrustean bed that limits our perception. I prefer
thinking of the type indicators as a starting point for understanding a person
rather than a final answer.

How should we approach personality? Is personality something we may ever totally
understand? Will we finally have a total understanding of how the human mind
works? This question has troubled the mind of many a man over the course of
mankind. We attempt to answer this question in a multitude of fields.
Neuropsychology attempts to explain how we think with science. The humanities
use literature to describe the human condition. Religion provides principles for
how we should act when facing the world and all its suffering.

Phenomenology is the study of the human experience and consciousness.
MBTI is a phenomenological tool -- right from the beginning.
The assignment of a psychological type does not happen by a scientific process,
it is derived from the person's own experience and self-evaluation.

We should therefore not be surprised when people behave in a way that is not
consistent with their type -- as predicting human behavior was never in the
scope of the model.
Instead, we may utilize the theory for partial understanding.
Fortunately, a partial understanding of people is not bad! We rarely get to know
anyone completely.
Even our own mind can come to surprise us.
** A tool for expression
When I know the person I am communicating with, I can tailor the way I act. In a
meaningful conversation, the medium is suitable for the topic, the communicator
and the listener.

1. *The topic* should be possible to discuss within the bounds of the mode of
   communication. Being overly scientific in ones mindset will limit one's
   ability to appreciate art. Attempting to understand theoretical mathematics
   purely through feelings is rarely effective.
2. *The communicator* should master the mode of communication. This is rarely a
   problem. People usually do things they are comfortable doing. It may even be
   a good idea to try to step outside of the mode of communication one is
   comfortable with, which enables learning.
3. *The receiver* must be able to understand what is being said. The
   communicator must therefore use language within the grasp of the listener.

A topic can often be approached through several different modes of
communication.
If this is the case, the communicator may tailor his mode of communication to
the listener.
When speaking to a person interested in people, talk about the effects on
people.
If the listener prefers scientific rigor, attempt to make a principled argument.

I have learned through experience to tailor my mode of communication to the
person I am speaking with.
If I simply let my thoughts flow into the room, I often face confused faces.
By moderating abstract arguments into something more specific, I am able to
reach a broader argument.
Being more explicit in one's assumptions can also help avoid what may appear to
be sudden leaps.

MBTI can be used as a tool to understand what mode of communication is
appropriate for the conversation. For an audience strong on sensing (S),
thoughts should be concretized as much as possible, and metaphysical arguments
avoided. For feelers (F), discuss how the decision will impact people.
** From type to mode of being
Reading up on the theory may give the impression that /one/ class is right for each
person.
I believe a slightly more nuanced understanding is in place.
Every person changes continuously with their environment.
When we sit and think deeply about a topic for a while, we will not be too
talkative when finally going into a room full of people.
By striking up random conversations, putting our body in motion and doing
improvisational exercises, we loosen up.
Sure, we may have an overall preference.
But that does not mean we do not adapt to situations!

I propose taking the profile as a mode of being.
Introverted people can become engaged in conversations.
Thinkers may enjoy being engulfed in feelings.
If we so choose.
And we can!
If we choose that we are bounded by our type, we may be.
If we take the type as a mode of being we revert to without conscious effort, we
can /make conscious effort/ to exit the bounds of our type.
** Different modes of being are preferred in different situations
When would it be useful to choose to go outside our usual preference?
When the situation calls for it.
Our circumstances change all the time, and each has a different demand.
Meeting lots of new people to have some fun?
Whip out your ESFP tendencies.
Be smooth.
Let the conversation flow.
Enjoy people's feelings.
Later that night, is the conversation turning philosophical over a good single
malt?
Allow that NT in the door.
** Use your type to improve your weaknesses
When you don't make an effort, you will fit in your type and follow your
preference. Go out of your comfort zone and try other modes of being to improve
on the places where you are weak.

If MBTI gives a preference for your action, that preference is typically where
you excel.
Is that the only thing you want to excel at?
Are you content with your primary mode of being?
Or do you want to thread the waters on the edge of your capacity?

MBTI can help you perceive where you have something to learn from others.
Where you can benefit from paying attention to how others act; where they may do
things in a way superior to your own.
** References                                                     :noexport:
[fn:16personalities]: [[https://www.16personalities.com][16 Personalities]] offers a free test to determine your Myers Briggs Type Indicator, descriptions of 16 types predicted by the test, and an overview on the underlying theory.

[fn:wikipedia-mbti-criticism]: TODO link. Quote from overview, link to criticism-specific section.
